# substitutions:
#     _DOCKER_GOLANG_VERSION: 1.0
steps:
- id: "Rodando teste"
  name: 'gcr.io/cloud-builders/go'
  args: ['go', 'test', '-v', './test/*.go']

# - id: "Gerando imagem"
#   name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '--build-arg'
#     - 'DOCKER_GOLANG_VERSION=${_DOCKER_GOLANG_VERSION}'
#     - '-t'
#     - 'gcr.io/$PROJECT_ID/docker-golang:latest'
#     - '-t'
#     - 'gcr.io/$PROJECT_ID/docker-golang:${_DOCKER_GOLANG_VERSION}'
#     - '.'

# - id: "Publicando imagem"
#   name: 'gcr.io/$PROJECT_ID/docker-golang'
#   args: ['version']

# images:
#   - 'gcr.io/$PROJECT_ID/docker-golang:latest'
#   - 'gcr.io/$PROJECT_ID/docker-golang:${_DOCKER_GOLANG_VERSION}'
# tags: ['cloud-builders-community']