# 2.07 MB
FROM golang:alpine AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -ldflags '-w -s' -a -installsuffix cgo -o /go/main .

FROM scratch

COPY --from=builder /go/main /go/main

ENTRYPOINT ["/go/main"]